library(rgdal)
library(sp)
library(raster)
library(rgeos)
library(stringr)
library(dplyr)
setwd("C:/Users/Carmen/Box Sync/EPIC-Biomass/GIS Data/Gonzalez Data")
PG_biomass <- raster("California_above_biomass_2010.tif")
PG_analysis <- raster("California biomass 2010 analysis.tif")
plot(PG_biomass)
plot(PG_analysis)
crs(PG_biomass)
crs(PG_analysis)

setwd("C:/Users/Carmen/Box Sync/EPIC-Biomass/GIS Data/LEMMA_gnn_sppsz_2014_08_28/")
LEMMA <- raster("mr200_2012")
crs(LEMMA)
plot(LEMMA)

EPSG <- make_EPSG()
maybe <- subset(EPSG, code == 5070)

