---
title: "Mortality Biomass Estimation README"
author: "Carmen Tubbesing"
date: "February 3, 2017"
output: 
  github_document:
    toc: TRUE
---
# Assumptions
2.  Aerial detection surveys (ADS) accurately assess the number of dead dominant and codiminant trees in each polygon and the size of each polygon.
3. LEMMA GNN accurately estimates the average size and species trees in each 30 x 30 m pixel. 
4. Dead trees in an ADS polygon are evenly distributed across the whole polygon, excluding parts of the polygon where LEMMA GNN shows no live trees 
5. All dead trees in a given LEMMA GNN pixel are of the most common tree species in that pixel
7. The diameter of every dead tree in a pixel is equal to the quadratic mean diameter of dominant and codominant trees in that pixel, as calculated by FIA data and represented in LEMMA GNN model results.

# Projection
All results should be projected in the coordinate reference system EPSG: 5070.

# File Organization
- R code assumes the user has the following located in their home directory:
    - Box Sync folder "EPIC-Biomass" with all GIS data
    - Clone of the cec_apl git repository
- Source data is located in *Box Sync/EPIC-Biomass/GIS Data*
- The *cec_apl/Biomass/R_scripts* folder contains all relevant scripts to perform the calculations, most importantly:
    - calculate dead tree biomass for the **whole state** from LEMMA and drought mortality data: *wholestate_noBA.R*
    - calculate dead tree biomass for **individual management units**: *units_calc_noBA.R*
    - calculate **live biomass** from LEMMA GNN (representing 2012 remote sensing data): *LEMMA_live_units_step1.R* and *LEMMA_live_units_step2.R*
    
# Sources

### Datasets
1.  `LEMMA`: GNN species-size raster data (*LEMMA_gnn_sppsz_2014_08_28*)
    - Download and variable descriptions can be found [here](http://lemma.forestry.oregonstate.edu/data/structure-maps)
    - State-wide estimates of tree species composition, size, biomass, etc.
    - Methods described in LEMMA_readme.pdf in the same Box Sync folder as LEMMA data
    - Empirical FIA plot data was assigned to every 30 x 30 m pixel in California based on similaries between remote sensing results for that pixel and the FIA plot
    - Each raster value is an FIA plot ID
        - each plot ID has many corresponding pixels
        - characteristics of plot IDs are described in the attribute table
2.  `drought`: Drought mortality polygons (*DroughtTreeMortality.gdb*)
    - Aerial detection survey results from manually recording tree mortality from aircraft
    - Methods described [here](http://www.fs.usda.gov/detail/r5/forest-grasslandhealth/?cid=fsbdev3_046721)

### References
1.  Jenkins, J. C., D. C. Chojnacky, L. S. Heath, and R. A. Birdsey. "National-scale biomass estimators for United States tree species." For. Sci., vol. 49, no. 1, pp. 12-35, 2003.
    - Includes equations predicting biomass based on diameter at breast height for major classes of tree species
    - These equations were used to estimate biomass in drought mortality polygons
      
# Process and Scripts Order
Data from LEMMA and drought mortality polygons were combined to estimate dead tree biomass. The steps can be summarized as follows, with the script performing each task in parentheses:

## Setup for both analyses
1. Crop `LEMMA` data to include only California (*1_crop_LEMMA.R*)
2. Transform ADS data to the same crs as `LEMMA` and save it as .Rdata for easier loading (*2_transform_ADS.R*)

## Setup specific to whole-state analysis
1.  Trim `drought` to exclude polygons that are 2 acres or smaller and/or have only 1 dead tree in them

## Setup specific to management units analysis
1. Crop FS management unit boundaries to include only units of interest and transform to same crs as `LEMMA` (*crop_FS.R*)
2. Crop NPS boundaries to Lassen and save (*crop_lnp.R*)
3. Combine unit layers that can be combined and save (*units_overlay.R*)
4. Calculate live biomass from LEMMA GNN data by averaging component ratio method biomass of trees > 2.5 cm dbh across all LEMMA GNN pixels with >0 biomass (*LEMMA_live_units_step1* and *LEMMA_live_units_step2*)

## Dead biomass calculations
1.  Create vectors of parameters for diameter -> biomass equations for each tree class based on Jenkins equations
2.  For each polygon
    1)  crop `LEMMA` to the size and shape of the polygon
    2)  extract coordinates of each `LEMMA` pixel that falls within the polygon
    3) extract corresponding FIA plot IDs for each `LEMMA` pixel in the polygon
    4) for each pixel within the polygon
        1. assign a diameter -> biomass equation based on the most common tree species in that pixel
        2. calculate average per-tree biomass using the above equation and the quadratic mean diameter of dominant and codominant trees (from `LEMMA`)
    5) combine these results into a data frame with one row
    6) bind the data frame to that of other polygons
7. Create a unique key for each pixel 
8. Write results to .csv file

# Output Variables 
| Code          |       Description  | Source(s) of data                |
|:--------------|:-------------------|:---------------------------------|
|   `key`         |       Unique pixel ID|     Analysis                   |
|   `x`           |       X coordinate of pixel center |     `LEMMA`        |    
|   `y`           |       Y coordinate of pixel center |     `LEMMA`        |
|   `D_BM_kg`  |       Estimated biomass of dead trees in the pixel in kg | `LEMMA` & `drought` |     
| `relNO`         | Approximate number of dead trees in pixel | Number of dead trees from `drought` (`Pol.NO_TREE`), divied up based on `relBA` (below)|
| `relBA`         | Pixel basal area (`BA_GE_3`)  relative to sum of `BA_GE_3` of all pixels in the polygon |  `LEMMA`
| `PlotID`          |       Corresponding FIA plot ID|       `LEMMA`          |
| `Pol.ID`        |        Polygon ID |    Analysis |
| `Pol.x`         | X coordinate of polygon centroid | `drought` |
| `Pol.y`         | Y coordinate of polygon centroid | `drought` |
| `RPT_YR`        | Year mortality was reported              | `drought` |
| `Pol.NO_TREE`   | Number of dead trees in the polygon | `drought` |
| `Pol.Shap_Ar`   | Area of polygon in square meters    | `drought` |
| `D_Pol_BM_kg`| Polygon dead biomass in kg, sum of `D_BM_kg` of all pixels in the polygon | `LEMMA` & `drought` |
| `All_BM_kgha`| Biomass density of all trees >= 2.5 cm dbh, dead or alive (`BPHC_GE_3_CRM`) |`LEMMA`|
| `All_Pol_BM_kgha` | Average density of all trees (mean `ALL_BM_kgha` of all pixels in polygon) | `LEMMA`|
| `THA`       | Trees >=2.5 cm dbh per hectare, dead or alive (`TPH_GE_3`) | `LEMMA`|
| `QMD_DOM`      | Quadratic mean diameter in cm of dominant and codominant trees | `LEMMA`|
| `TREEPL`         | Most common tree species in the pixel | `LEMMA` |
| `Av_BM_TR`      | Average per-tree biomass of dead trees, in kg (`D_Pol_CONBM_k`/`Pol.NO_TREE`) | `LEMMA` & `drought` |
| `All_Pol_NO`| Total number of trees in the polygon, from `Pol.Shap_Ar` and `THA` | `LEMMA`|
| `All_Pol_BM`| Total trees in the polygon, from `Pol.Shap.Ar` and `All_Pol_CONBM_kgha` | `LEMMA` |

# Tests
The following tests were performed on a randomly selected polygon within `drought` in the file *R_scripts/tests/test.R* to check for accuracy of the results. When *test.R* is run, lines 82-92 should all individually return `TRUE`.

1. `relBA` calculated by hand outside the for loop for a randomly selected pixel within the polygon equals `relBA` from loop results
2. `relNO` from loop results equals `relBA` * number of dead trees in pixel calculated by hand
3. Pixels within 50 m of the polygon's centroid have the same raster values and X and Y coordinates as those produced by the loop
4. Biomass of dead trees in the pixel calculated by hand matches loop results
5. `All_BM_kgha` from results matches attribute data in LEMMA
6. `All_Pol_BM_kgha` from results equals the mean of `All_BM_kgha` for all pixels in the polygon
7. `Pol.x` and `Pol.y` from results match `coordinates()` of the polygon
8. `Pol.NO_TREE` from results matches the sum of `relNO` for all pixels
9. `All_Pol_NO` from results matches the sum of per pixel calculated by hand from `TPHC_GE_3`
